import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Diátaxis + dual handbook: P1–P4 capability guides + package module manuals.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: 'category',
      label: '开始',
      collapsed: false,
      items: [
        'getting-started',
        'getting-started-en',
        'tutorial/quickstart',
        'guide/onboarding-three-paths',
        'faq/index',
        'glossary/index',
      ],
    },
    {
      type: 'category',
      label: '手册',
      link: {type: 'doc', id: 'guide/index'},
      items: [
        'guide/overview',
        'guide/role-based-paths',
        {
          type: 'category',
          label: '选型 · P1–P4',
          collapsed: false,
          items: [
            {
              type: 'category',
              label: 'P1 化学与嵌入',
              collapsed: true,
              items: [
                'guide/chemistry-and-embedding',
                'guide/dual-classical-ingress',
                'guide/fermion-qubit-mappings',
                'guide/avas-casscf-workflow',
                'guide/backend-adapter-quickstart',
                'guide/psi4-backend',
              ],
            },
            {
              type: 'category',
              label: 'P2 算法与协议',
              collapsed: true,
              items: [
                'guide/program-construction',
                'guide/algorithm-and-ansatz-menu',
                'guide/operator-pools-adapt-iqeb',
                'guide/pauli-protocol-and-shots',
                'guide/excited-states-vqd-qse-sceom',
                'guide/gqe-generative-eigensolver',
              ],
            },
            {
              type: 'category',
              label: 'P3 执行与分析',
              collapsed: true,
              items: [
                'guide/execution-and-analysis',
                'guide/backends-and-profiles',
                'guide/mitigation-zne-shadows',
                'guide/md-ml-active-learning',
                'guide/resource-estimation-methods',
              ],
            },
            {
              type: 'category',
              label: 'P4 作业与可复现',
              collapsed: true,
              items: [
                'guide/jobs-and-reproducibility',
                'guide/parity-repro-contract',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: '模块手册',
          link: {type: 'doc', id: 'modules/index'},
          collapsed: false,
          items: [
            'modules/reading-paths',
            'modules/config',
            {
              type: 'category',
              label: 'chem',
              link: {type: 'doc', id: 'modules/chem/index'},
              items: [
                'modules/chem/mappings',
                'modules/chem/hamiltonian',
                'modules/chem/avas-casscf',
                'modules/chem/dual-ingress',
                'modules/chem/embedding',
                'modules/chem/embedding-dmet',
                'modules/chem/embedding-projection',
                'modules/chem/embedding-schmidt',
                'modules/chem/solvers',
              ],
            },
            {
              type: 'category',
              label: 'quantum',
              link: {type: 'doc', id: 'modules/quantum/index'},
              items: [
                {
                  type: 'category',
                  label: '算法深读',
                  link: {type: 'doc', id: 'modules/quantum/algorithms/index'},
                  collapsed: true,
                  items: [
                    'modules/quantum/algorithms/vqe-hea',
                    'modules/quantum/algorithms/uccsd',
                    'modules/quantum/algorithms/adapt-vqe',
                    'modules/quantum/algorithms/iqeb',
                    'modules/quantum/algorithms/iqcc',
                    'modules/quantum/algorithms/qcc-paired',
                    'modules/quantum/algorithms/sa-vqe',
                    'modules/quantum/algorithms/uccgd',
                    'modules/quantum/algorithms/qite',
                    'modules/quantum/algorithms/vsqs-ansatz',
                    'modules/quantum/algorithms/research-ansatze',
                    'modules/quantum/algorithms/vqd',
                    'modules/quantum/algorithms/qse',
                    'modules/quantum/algorithms/sceom',
                    'modules/quantum/algorithms/qpe',
                    'modules/quantum/algorithms/vqs',
                    'modules/quantum/algorithms/gqe',
                    'modules/quantum/algorithms/custom-plugin',
                    'modules/quantum/algorithms/operator-pools',
                    'modules/quantum/algorithms/pauli-protocol',
                  ],
                },
                'modules/quantum/ansatz-algorithms',
                'modules/quantum/adapt-iqeb',
                'modules/quantum/excited-states',
              ],
            },
            {
              type: 'category',
              label: 'backends',
              link: {type: 'doc', id: 'modules/backends'},
              items: [
                'modules/backends/statevector',
                'modules/backends/qiskit',
                'modules/backends/uqc',
                'modules/backends/other-providers',
              ],
            },
            'modules/protocols',
            'modules/orchestration',
            'modules/mitigation',
            'modules/md-bridge',
            'modules/ops-light',
            'modules/jobs',
            'modules/repro',
            'modules/api-sdk',
            'modules/integrations',
            'modules/contracts',
            'modules/tensornet',
          ],
        },
        'guide/principles-and-reading',
      ],
    },
    {
      type: 'category',
      label: '示例',
      collapsed: true,
      items: ['examples/index', 'examples/gallery-body'],
    },
    {
      type: 'category',
      label: '教程',
      link: {type: 'doc', id: 'tutorial/index'},
      items: [
        'tutorial/index',
        'tutorial/verify-block-template',
        'tutorial/quickstart',
        'tutorial/workflow',
        'tutorial/decomposition-plugin-minimal',
        'tutorial/async-run-via-http',
        'tutorial/read-repro-keys',
        'tutorial/switch-backend-compare',
        'tutorial/uccsd-trotter-export',
        'tutorial/gqe-nakaji-h2',
        'tutorial/adapt-pool-smoke',
        'tutorial/qpe-track',
        'tutorial/dmet-self-consistent',
        'tutorial/gqe-variants',
        'tutorial/oniom-smoke',
        'tutorial/zne-qiskit-repro',
        'tutorial/projection-embedding-deep-dive',
        'tutorial/case-study-h2-family',
        'tutorial/casscf-audit-workflow',
        'tutorial/md-ml-active-learning',
        'tutorial/tutorial-index-three-paths',
      ],
    },
    {
      type: 'category',
      label: '参考',
      items: [
        'reference/python-sdk',
        'reference/api-generated',
        'reference/api-surface',
        'reference/cli-and-scripts',
        'reference/cli-http',
        'reference/openapi',
        'reference/http-api-sqlite-jobs',
        'reference/install-profiles',
        'reference/configs-catalog',
        'reference/tutorial-config-matrix',
        'faq/index',
        {
          type: 'category',
          label: '配置字段',
          link: {type: 'doc', id: 'reference/config-fields/index'},
          items: [
            'reference/config-fields/molecule',
            'reference/config-fields/scf',
            'reference/config-fields/active-space',
            'reference/config-fields/embedding',
            'reference/config-fields/quantum',
            'reference/config-fields/backend',
            'reference/config-fields/mitigation',
            'reference/config-fields/compiler',
            'reference/config-fields/chemistry-extended',
            'reference/config-fields/sidecars',
          ],
        },
        'reference/pre-quantum-yaml-matrix',
        'reference/docs-versioning',
        'reference/circuitir-tket-jobs',
        'reference/qiskit-shot-counts',
        'reference/dmet-parity-snapshot',
        'reference/parity-contract-import-paths',
        'parity/public-matrix',
        'parity/gaps',
        'parity/gap-implementation-plan',
      ],
    },
    {
      type: 'category',
      label: '概念与产品',
      items: [
        'concept/docs-information-architecture',
        'concept/engineering-architecture',
        'product/features',
        'product/capability-sla',
        'product/positioning',
        'product/non-goals',
        'product/roadmap',
      ],
    },
    {
      type: 'category',
      label: '云与运维',
      items: [
        'cloud/overview',
        'cloud/tenant-and-quotas',
        'cloud/backend-registry',
        'cloud/jobs-and-logs',
        'cloud/uqc-backend',
        'release/deployment-checklist',
        'changelog/index',
      ],
    },
  ],
};

export default sidebars;
