"""Docs sync: examples gallery + tutorial verify blocks."""

from __future__ import annotations

import runpy
import subprocess
import sys

from tests.helpers.paths import repo_root


def test_examples_gallery_generator_check_mode() -> None:
    root = repo_root()
    script = root / "scripts" / "generate_examples_gallery.py"
    # Ensure generated artifacts exist first.
    subprocess.run([sys.executable, str(script)], cwd=str(root), check=True)
    proc = subprocess.run(
        [sys.executable, str(script), "--check"],
        cwd=str(root),
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, proc.stderr or proc.stdout
    body = root / "docusaurus-site" / "docs" / "examples" / "gallery-body.md"
    assert body.is_file()
    text = body.read_text(encoding="utf-8")
    assert "generated by scripts/generate_examples_gallery.py" in text
    assert "tutorial_01_h2_vqe_export.py" in text


def test_tutorial_verify_blocks_script_passes() -> None:
    root = repo_root()
    script = root / "scripts" / "check_tutorial_verify_blocks.py"
    proc = subprocess.run(
        [sys.executable, str(script)],
        cwd=str(root),
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, proc.stderr or proc.stdout


def test_algorithm_deep_read_coverage_script_passes() -> None:
    root = repo_root()
    script = root / "scripts" / "check_algorithm_deep_read_coverage.py"
    proc = subprocess.run(
        [sys.executable, str(script)],
        cwd=str(root),
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, proc.stderr or proc.stdout


def test_tutorial_verify_block_helpers_via_runpy() -> None:
    root = repo_root()
    ns = runpy.run_path(str(root / "scripts" / "check_tutorial_verify_blocks.py"))
    sample = "## 验证命令\n\n```bash\necho ok\n```\n\n## 期望输出\n\n- exit 0\n"
    assert ns["_section_after"](sample, ns["VERIFY_HEADINGS"]) is not None
    assert ns["_has_fence"](ns["_section_after"](sample, ns["VERIFY_HEADINGS"]))
