#!/usr/bin/env python3
"""Generate Docusaurus capability SLA docs from ``product_capability_sla_v1()``.

Writes:
  - docusaurus-site/docs/product/capability-sla-body.md  (generated table body)
  - docusaurus-site/docs/product/capability-sla.md       (page with frontmatter + body)

Usage:
  python scripts/generate_capability_sla_md.py
  python scripts/generate_capability_sla_md.py --check
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_BODY = ROOT / "docusaurus-site" / "docs" / "product" / "capability-sla-body.md"
OUT_PAGE = ROOT / "docusaurus-site" / "docs" / "product" / "capability-sla.md"

_GEN_BANNER = "{/* generated by scripts/generate_capability_sla_md.py; do not edit */}\n\n"


def _build_body() -> str:
    sys.path.insert(0, str(ROOT / "src"))
    from qchem_stack.protocols.product_contract import product_capability_sla_v1

    payload = product_capability_sla_v1()
    lines: list[str] = [
        _GEN_BANNER,
        "> **Source of truth:** `qchem_stack.protocols.product_contract.product_capability_sla_v1()`. "
        "Regenerate with `python scripts/generate_capability_sla_md.py`.\n",
        "",
        "Normalized SLA labels: `available` · `partial` · `stub_only` · `n/a` · `local_runtime_only`.",
        "",
        "| Capability id | Raw status | SLA | Surface |",
        "|---------------|------------|-----|---------|",
    ]
    for row in payload["rows"]:
        surface = str(row.get("open_stack_surface") or "").replace("|", "\\|")
        if len(surface) > 120:
            surface = surface[:117] + "..."
        lines.append(f"| `{row['id']}` | `{row['status']}` | **{row['sla']}** | {surface} |")
    lines.extend(
        [
            "",
            "## Stub warnings at config load",
            "",
            "When a YAML enables a clearly stub-oriented path, config validation emits "
            "`logging.warning` (does not hard-fail):",
            "",
            "- `quantum.tensornet.expectation_stub: true` — CuTensorNet expectation stub",
            "- `mitigation.stubs.classical_shadows: true` — classical-shadows stub-labeled "
            "node (computable runtime may still attach; treat as research / non-SLA)",
            "",
            "See `qchem_stack.config._experiment_validation.warn_stub_config_features`.",
            "",
        ]
    )
    return "\n".join(lines)


def _build_page(body: str) -> str:
    # Strip the JS comment banner from the inlined body (page has its own frontmatter).
    body_core = body
    if body_core.startswith("{/*"):
        body_core = body_core.split("\n", 2)[-1]
    return (
        "---\n"
        "title: 能力 SLA\n"
        "description: Product capability SLA labels derived from PRODUCT_GAP_CATEGORIES_V1.\n"
        "keywords:\n"
        "  - capability\n"
        "  - SLA\n"
        "  - product gaps\n"
        "---\n\n"
        "{/* generated by scripts/generate_capability_sla_md.py; do not edit */}\n\n"
        "# 能力 SLA\n\n"
        "本页把产品缺口表（`PRODUCT_GAP_CATEGORIES_V1`）规范化为发布面可用的 SLA 标签，"
        "便于对外说明「可用 / 部分 / 仅 stub / 不适用 / 仅本地运行时」。\n\n"
        f"{body_core.strip()}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated files would change",
    )
    args = parser.parse_args()

    body = _build_body()
    page = _build_page(body)
    planned = ((OUT_BODY, body), (OUT_PAGE, page))

    if args.check:
        for path, text in planned:
            if not path.is_file():
                print(f"missing {path}; run without --check", flush=True)
                return 1
            if path.read_text(encoding="utf-8") != text:
                print(
                    f"stale {path}; run: python scripts/generate_capability_sla_md.py", flush=True
                )
                return 1
        print("capability SLA docs sync OK")
        return 0

    for path, text in planned:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
