#!/usr/bin/env python3
"""Generate Docusaurus examples gallery body from ``examples/README.md``.

Writes:
  - docs/generated/examples_gallery_snippet.md
  - docusaurus-site/docs/examples/gallery-body.md

Usage:
  python scripts/generate_examples_gallery.py
  python scripts/generate_examples_gallery.py --check
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "examples" / "README.md"
OUT_REPO = ROOT / "docs" / "generated" / "examples_gallery_snippet.md"
OUT_DOCUSAURUS = ROOT / "docusaurus-site" / "docs" / "examples" / "gallery-body.md"

# Rewrite repo-relative markdown links so they work from the docs site.
_LINK_REWRITES: list[tuple[re.Pattern[str], str]] = [
    (
        re.compile(r"\]\(\.\./CONTRIBUTING\.md\)"),
        "](https://github.com/sunhl4/qcchem-qml-md/blob/main/CONTRIBUTING.md)",
    ),
    (
        re.compile(r"\]\(\.\./docs/([^)]+)\)"),
        r"](https://github.com/sunhl4/qcchem-qml-md/blob/main/docs/\1)",
    ),
    (
        re.compile(r"\]\(\.\./docusaurus-site/docs/guide/onboarding-three-paths\.md\)"),
        "](/guide/onboarding-three-paths)",
    ),
    (
        re.compile(r"\]\(\.\./docusaurus-site/docs/guide/chemistry-and-embedding\.md\)"),
        "](/guide/chemistry-and-embedding)",
    ),
]


def _rewrite_links(text: str) -> str:
    out = text
    for pattern, repl in _LINK_REWRITES:
        out = pattern.sub(repl, out)
    return out


def _build_markdown() -> str:
    raw = SRC.read_text(encoding="utf-8")
    body = _rewrite_links(raw).strip() + "\n"
    # Avoid competing with Docusaurus page title: demote README H1 → H2.
    if body.startswith("# "):
        body = "## " + body[2:]
    # Plain-text relative docs paths in bullets → GitHub URLs.
    body = re.sub(
        r"`\.\./docs/([^`]+)`",
        r"[`docs/\1`](https://github.com/sunhl4/qcchem-qml-md/blob/main/docs/\1)",
        body,
    )
    header = (
        "---\n"
        "title: 示例索引（自动同步）\n"
        "description: Synced from examples/README.md — do not edit by hand.\n"
        "---\n\n"
        "{/* generated by scripts/generate_examples_gallery.py; do not edit */}\n\n"
    )
    note = (
        "> **Source of truth:** repository [`examples/README.md`]("
        "https://github.com/sunhl4/qcchem-qml-md/blob/main/examples/README.md). "
        "Regenerate with `python scripts/generate_examples_gallery.py`.\n\n"
    )
    return header + note + body


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if generated files would change",
    )
    args = parser.parse_args()

    if not SRC.is_file():
        print(f"missing {SRC}", flush=True)
        return 1

    new_text = _build_markdown()
    outputs = (OUT_REPO, OUT_DOCUSAURUS)
    if args.check:
        for out in outputs:
            if not out.is_file():
                print(f"missing {out}; run without --check", flush=True)
                return 1
            if out.read_text(encoding="utf-8") != new_text:
                print(f"stale {out}; run: python scripts/generate_examples_gallery.py", flush=True)
                return 1
        print("examples gallery sync OK")
        return 0

    for out in outputs:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(new_text, encoding="utf-8")
        print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
