#!/usr/bin/env python3
"""Generate tutorial ↔ config matrix for docs (which YAML have tutorials)."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TUTORIAL_DIR = ROOT / "docusaurus-site" / "docs" / "tutorial"
CONFIGS = ROOT / "configs"
OUT = ROOT / "docusaurus-site" / "docs" / "reference" / "tutorial-config-matrix.md"

CONFIG_RE = re.compile(
    r"configs/(?:scenarios/)?([A-Za-z0-9_\-]+\.ya?ml)|"
    r"`((?:example_|tutorial_|benchmark_)[A-Za-z0-9_\-]+\.ya?ml)`|"
    r"(?<![\w/])((?:example_|tutorial_)[A-Za-z0-9_\-]+\.ya?ml)"
)


def _scan_tutorials() -> dict[str, set[str]]:
    """config basename -> set of tutorial page stems that mention it."""
    mapping: dict[str, set[str]] = {}
    for path in sorted(TUTORIAL_DIR.glob("*.md")):
        if path.name in {"index.md", "tutorial-index-three-paths.md"}:
            continue
        text = path.read_text(encoding="utf-8")
        stem = path.stem
        for m in CONFIG_RE.finditer(text):
            name = m.group(1) or m.group(2) or m.group(3)
            if not name:
                continue
            mapping.setdefault(name, set()).add(stem)
    return mapping


def _cluster(name: str) -> str:
    n = name.lower()
    if "gqe" in n:
        return "GQE"
    if "adapt" in n or "iqeb" in n or "tetris" in n:
        return "ADAPT / IQEB"
    if (
        "dmet" in n
        or "projection" in n
        or "schmidt" in n
        or "oniom" in n
        or "avas" in n
        or "casscf" in n
    ):
        return "Embedding / AVAS"
    if "vqd" in n or "qse" in n or "sceom" in n or "excited" in n:
        return "Excited"
    if "qpe" in n:
        return "QPE"
    if "md" in n or "qmlff" in n or "uqc" in n:
        return "MD / UQC"
    if "uccsd" in n or "vqe" in n or "hea" in n or name.startswith("example_h2.yaml"):
        return "VQE / UCC"
    if "zne" in n or "pauli" in n or "qiskit" in n or "sampled" in n:
        return "Measure / mitigation"
    return "Other"


def _build() -> str:
    tut_map = _scan_tutorials()
    top_yaml = sorted(p.name for p in CONFIGS.glob("*.yaml"))
    lines = [
        "---",
        "title: 配置 ↔ 教程矩阵",
        "description: 哪些 configs/*.yaml 被教程引用；其余为 catalog-only smoke。",
        "---",
        "",
        "{/* generated by scripts/generate_tutorial_config_matrix.py; do not edit */}",
        "",
        "# 配置 ↔ 教程矩阵",
        "",
        "由 `python3 scripts/generate_tutorial_config_matrix.py` 生成。"
        "有教程 = 至少一篇 `docs/tutorial/*.md` 提到该文件名；否则为 **仅 smoke / catalog**。",
        "",
        f"**统计：** 顶层 YAML {len(top_yaml)}；被教程引用 {len(tut_map)}。",
        "",
        "## 按能力簇（有教程）",
        "",
    ]
    by_cluster: dict[str, list[str]] = {}
    for name in sorted(tut_map):
        by_cluster.setdefault(_cluster(name), []).append(name)

    for cluster in sorted(by_cluster):
        lines.append(f"### {cluster}")
        lines.append("")
        lines.append("| 配置 | 教程页 |")
        lines.append("|------|--------|")
        for name in by_cluster[cluster]:
            tuts = ", ".join(f"[`{t}`](/tutorial/{t})" for t in sorted(tut_map[name]))
            lines.append(f"| `{name}` | {tuts} |")
        lines.append("")

    uncovered = [n for n in top_yaml if n not in tut_map]
    lines.extend(
        [
            "## 仅 smoke / catalog（无教程引用）",
            "",
            f"共 **{len(uncovered)}** 个顶层 YAML。完整列表见 [配置目录](./configs-catalog)。",
            "",
            "<details>",
            "<summary>展开文件名</summary>",
            "",
        ]
    )
    for n in uncovered:
        lines.append(f"- `{n}`")
    lines.extend(["", "</details>", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    body = _build()
    if args.check:
        if not OUT.is_file() or OUT.read_text(encoding="utf-8") != body:
            print(
                f"stale {OUT}; run: python3 scripts/generate_tutorial_config_matrix.py", flush=True
            )
            return 1
        print("tutorial-config matrix OK", flush=True)
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
