#!/usr/bin/env python3
"""Generate docs/generated/parity_gap_snippet.md from product_contract gaps."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "generated" / "parity_gap_snippet.md"


def render_snippet() -> str:
    from qchem_stack.protocols.product_contract import product_gap_categories

    rows = product_gap_categories()
    lines = [
        "<!-- AUTO-GENERATED by scripts/generate_parity_gap_snippet.py; do not edit -->",
        "",
        "## Capability gaps (machine-readable)",
        "",
        "| id | status | release_anchor |",
        "|----|--------|----------------|",
    ]
    for row in rows:
        gid = str(row.get("id", ""))
        status = str(row.get("status", ""))
        anchor = str(row.get("release_anchor", ""))
        lines.append(f"| `{gid}` | {status} | {anchor} |")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    text = render_snippet()
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        if not OUT.is_file():
            print(f"missing {OUT}", file=sys.stderr)
            return 1
        if OUT.read_text(encoding="utf-8") != text:
            print(f"stale {OUT}; run: python {Path(__file__).name}", file=sys.stderr)
            return 1
        print("parity_gap_snippet OK")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
