#!/usr/bin/env python3
"""Generate configs catalog snippets for docs (reduces manual count drift)."""

from __future__ import annotations

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIGS = ROOT / "configs"
OUT_REPO = ROOT / "docs" / "generated" / "configs_catalog_snippet.md"
OUT_DOCUSAURUS = ROOT / "docusaurus-site" / "docs" / "reference" / "configs-catalog-body.md"


def _classify(path: Path) -> str:
    import yaml

    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if isinstance(data, dict) and data.get("max_rounds") and data.get("force_field_backend"):
        return "md"
    return "experiment"


def _build_markdown() -> list[str]:
    yaml_files = sorted(CONFIGS.glob("*.yaml"))
    exp = [p for p in yaml_files if _classify(p) == "experiment"]
    md = [p for p in yaml_files if _classify(p) == "md"]
    profiles = (
        sorted((CONFIGS / "profiles").glob("*.yaml")) if (CONFIGS / "profiles").is_dir() else []
    )

    body_lines = [
        f"**Total:** {len(yaml_files)} top-level YAML "
        f"({len(exp)} ExperimentConfig + {len(md)} MdValidationLoopConfig). "
        f"Profiles: {len(profiles)} under `configs/profiles/`.",
        "",
        "## ExperimentConfig files",
        "",
    ]
    for p in exp:
        body_lines.append(f"- `{p.name}`")
    body_lines.extend(["", "## MdValidationLoopConfig files", ""])
    for p in md:
        body_lines.append(f"- `{p.name}`")
    return body_lines


def _with_header(body_lines: list[str], *, mdx: bool) -> str:
    if mdx:
        header = "{/* generated by scripts/generate_configs_catalog.py; do not edit */}"
    else:
        header = "<!-- generated by scripts/generate_configs_catalog.py; do not edit -->"
    return "\n".join([header, "", *body_lines]) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="Exit 1 if generated files would change"
    )
    args = parser.parse_args()

    body_lines = _build_markdown()
    outputs = (
        (OUT_REPO, False),
        (OUT_DOCUSAURUS, True),
    )
    if args.check:
        for out, mdx in outputs:
            expected = _with_header(body_lines, mdx=mdx)
            if not out.is_file():
                print(f"missing {out}; run without --check", flush=True)
                return 1
            if out.read_text(encoding="utf-8") != expected:
                print(f"stale {out}; run: python scripts/generate_configs_catalog.py", flush=True)
                return 1
        return 0
    for out, mdx in outputs:
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(_with_header(body_lines, mdx=mdx), encoding="utf-8")
        print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
