#!/usr/bin/env python3
"""Generate config scenario picker markdown for onboarding (8 core scenarios)."""

from __future__ import annotations

import argparse
from pathlib import Path

from qchem_stack.config.scenarios import SCENARIOS, list_scenarios_text

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docs" / "generated" / "config_picker.md"


def build_markdown() -> str:
    lines = [
        "<!-- generated by scripts/generate_config_picker.py; do not edit -->",
        "",
        "# Config scenario picker",
        "",
        "Pick a **scenario** first, then open a representative YAML under `configs/`.",
        "",
        "| Scenario | Use when | Representative configs |",
        "|----------|----------|------------------------|",
    ]
    for sid, (title, desc, yaml_names) in SCENARIOS.items():
        paths = ", ".join(f"`configs/{y}`" for y in yaml_names[:2])
        lines.append(f"| **{title}** (`{sid}`) | {desc} | {paths} |")
    lines.extend(
        [
            "",
            "## CLI",
            "",
            "```bash",
            "qchem-run --list-scenarios",
            "qchem-run configs/example_h2.yaml",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--print-scenarios", action="store_true")
    args = parser.parse_args()
    if args.print_scenarios:
        print(list_scenarios_text(), end="")
        return 0
    text = build_markdown()
    if args.check:
        if not OUT.is_file() or OUT.read_text(encoding="utf-8") != text:
            print(f"stale {OUT}; run without --check", flush=True)
            return 1
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
