#!/usr/bin/env python3
"""Generate SDK API reference MDX from qchem_stack.sdk.__all__."""

from __future__ import annotations

import argparse
import inspect
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "docusaurus-site" / "docs" / "reference" / "api-generated.md"


def _build() -> str:
    from qchem_stack import sdk

    names = list(getattr(sdk, "__all__", []))
    lines = [
        "---",
        "title: SDK API（生成）",
        "description: 由 scripts/generate_sdk_api_mdx.py 从 qchem_stack.sdk 内省生成。",
        "---",
        "",
        "{/* generated by scripts/generate_sdk_api_mdx.py; do not edit */}",
        "",
        "# SDK API（生成）",
        "",
        "稳定集成面 `qchem_stack.sdk` 的签名摘要。用法见 [Python SDK](./python-sdk) 与 [API 面](./api-surface)。",
        "",
        f"**符号数：** {len(names)}",
        "",
    ]
    for name in names:
        obj = getattr(sdk, name, None)
        lines.append(f"## `{name}`")
        lines.append("")
        if obj is None:
            lines.append("*missing on module*")
            lines.append("")
            continue
        try:
            sig = str(inspect.signature(obj)) if callable(obj) else ""
        except (TypeError, ValueError):
            sig = ""
        if callable(obj) and sig:
            lines.append(f"```python\n{name}{sig}\n```")
            lines.append("")
        doc = inspect.getdoc(obj) or ""
        if doc:
            # first paragraph only
            para = doc.strip().split("\n\n")[0].replace("\n", " ")
            lines.append(para)
            lines.append("")
        else:
            lines.append(f"Type: `{type(obj).__name__}`")
            lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    body = _build()
    if args.check:
        if not OUT.is_file() or OUT.read_text(encoding="utf-8") != body:
            print(f"stale {OUT}; run: python3 scripts/generate_sdk_api_mdx.py", flush=True)
            return 1
        print("sdk api mdx OK", flush=True)
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
